### ISSUE TITLE
Ignoring mask is impossible

### ISSUE THREAD

**Issue by konradkolod** [pirc-pl/pirc-gateway#9]
It is impossible to ignore masks for example *!*@*master.of.puppets. However it is standard function of all irc clients. Furthermore, there is inscription "mask" in the window of ignored users list. It is misleading, user think it is possible to add masks to ignored users list.

**Comment by k4bek4be** [comment]
Will be changed.

**Comment by k4bek4be** [comment]
Done in 733e7b05621f434c1b5c8e7f4c2cda2886d0d74e
